# Generated by Django 3.2.8 on 2021-11-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
