# Generated by Django 3.2.8 on 2021-11-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_reviews_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
